# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- feature/*
- fix/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: Debug
  buildCounter: 1
  buildNumber: $[counter(variables['buildCounter'], 0)]

steps:

# build project
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: './src/Pype/Pype.csproj'
    arguments: '--configuration $(buildConfiguration) --version-suffix develop-$(buildNumber)'

# make package
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'custom'
    custom: 'pack'
    projects: './src/Pype/Pype.csproj'
    arguments: '--configuration $(buildConfiguration) --version-suffix develop-$(buildNumber) --no-build --output $(Build.ArtifactStagingDirectory)'
