# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: Release
  version: 1.3.0 # needed to enable counter reset on version bump
  buildNumber: $[counter(variables['version'], 1)]
  artifactName: 'PypeNugetBeta'

steps:

# restore solution projects
- template: templates/solution-restore.yml

# build solution projects
- task: DotNetCoreCLI@2
  displayName: 'Build solution projects'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) /p:Version=$(version)-beta-$(buildNumber) --no-restore'

# test solution project
- template: templates/solution-test-collect-report.yml

# pack solution projects
- task: DotNetCoreCLI@2
  displayName: 'Pack solution projects'
  inputs:
    command: 'custom'
    custom: 'pack'
    arguments: '--configuration $(buildConfiguration) /p:Version=$(version)-beta-$(buildNumber) --no-restore --no-build --output $(Build.ArtifactStagingDirectory)'

# publish artifacts  
- template: templates/artifacts-publish.yml